name: test-suite

on:
  push:
    paths-ignore: ['**.rst']
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Install dylan-compiler and deft binaries in the current PATH.
      - uses: dylan-lang/install-opendylan@v3

      - name: Build and run test suite
        run: |
          export DYLAN="$(realpath dylan-root)"
          mkdir -p ${DYLAN}
          make test

      - name: Install
        run: |
          export DYLAN="$(realpath dylan-root)"
          mkdir -p ${DYLAN}
          make install

      - name: Exercise deft
        run: |
          export DYLAN="$(realpath dylan-root)"
          export PATH="${DYLAN}/bin:${PATH}"
          deft new library --force-package abc strings@1.1
          cd abc
          deft update
          deft status
          deft list
          deft build abc-test-suite
          _build/bin/abc-test-suite
