name: Makefile CI

on:
  push:
    branches:
      - github-ci
      - master
  pull_request:
    branches:
      - github-ci
      - master
  # This enables the Run Workflow button on the Actions tab. (Or does it?)
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Open Dylan
      run: |
          echo "Installing Open Dylan..."
          curl -L -o opendylan.tar.bz2 https://github.com/dylan-lang/opendylan/releases/download/v2020.1.0/opendylan-2020.1-x86_64-linux.tar.bz2
          tar xfj opendylan.tar.bz2
          echo -n "This is Open Dylan "
          opendylan-2020.1/bin/dylan-compiler -version

    # Build and run test suites as individual steps rather than just using
    # `make test`, so we get better feedback in the GitHub UI.

    - name: Build dylan-tool
      run: opendylan-2020.1/bin/dylan-compiler -build -jobs 3 dylan-tool

    - name: Build pacman-test-suite
      run: opendylan-2020.1/bin/dylan-compiler -build -jobs 3 pacman-test-suite

    - name: Run pacman-test-suite
      run: _build/bin/pacman-test-suite

    - name: Build workspaces-test-suite
      run: opendylan-2020.1/bin/dylan-compiler -build -jobs 3 workspaces-test-suite

    - name: Run workspaces-test-suite
      run: _build/bin/workspaces-test-suite
