name: test-suite

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: dylan-lang/install-opendylan@v3

      - name: test and install
        env:
          DYLAN_CATALOG: ext/pacman-catalog
          DYLAN: dylan-root
        run: |
          mkdir -p ${DYLAN}
          PATH=..:${PATH} make test
          PATH=..:${PATH} make install

      - name: Exercise dylan-tool
        env:
          DYLAN_CATALOG: ext/pacman-catalog
          DYLAN: dylan-root
        run: |
          dylan_exe=$(realpath ${DYLAN}/bin/dylan)
          export DYLAN_CATALOG=$(realpath ${DYLAN_CATALOG})
          ${dylan_exe} new library --force-package abc strings@1.1
          cd abc
          ${dylan_exe} update
          ${dylan_exe} status
          ${dylan_exe} list
          PATH=${GITHUB_WORKSPACE}/..:$PATH ${dylan_exe} build abc-test-suite
          _build/bin/abc-test-suite
